[package]
name = "example_lttb_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
minmaxlttb = { path = "../../minmaxlttb" }
csv = "1.3"
plotly = "0.13"
clap = { version = "4.5", features = ["derive"] }
